params:
    server_name: string
    partition_name: string
    total_space: integer
    free_space: integer
    use_space: integer
    use_percet_space: integer
    free_percent_space: integer

critical:
    when: (server_name == "my_server1" and free_space < 2) or (server_name == "my_server2" and free_space <= 7)
    repeat: 20
    email:
        tpl: You have the partition ${name} with ${free_percent_space} percent free